Change README for easier cp/paste installation.
ufs-community/uwtools pull request #313
Opened 2023-10-06 16:39 UTC by christinaholtNOAA

**Description**

Modifying the README so that it's easier to install miniforge by copying the lines installation lines directly into the command line. This approach should find the name of the installer script needed for the specific platform.

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation.  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-10-06 16:45 UTC, WeirAE approved these changes
Simple and clean, LGTM

2023-10-11 14:34 UTC, elcarpenterNOAA approved these changes
Helpful changes. LGTM.

2023-10-12 13:33 UTC, NaureenBharwaniNOAA approved these changes
LGTM!

2023-10-16 13:59 UTC, maddenp-noaa requested changes

2023-10-24 14:59 UTC, closed without merging